default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  host:     localhost
  pool: 5
  username: todo_rails_ng
  password:
  template: template0

development:
  <<: *default
  database: todo_rails_ng_dev

test:
  <<: *default
  database: todo_rails_ng_test
